import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

import { Inter } from "next/font/google";

// Configure Inter with common subsets and weights
const inter = Inter({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"], // Include the weights you need
    variable: "--font-inter", // Optional: Creates a CSS variable for Tailwind
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className={`min-h-screen ${inter.className}`}>
                <div className="grid grid-cols-[250px_1fr] grid-rows-[auto_1fr] min-h-screen">
                    {/* Sidebar (full height) */}
                    <aside className="row-span-2 bg-primary-500 text-white p-6">
                        <Sidebar />
                    </aside>

                    {/* Header (top right) */}
                    <header className="bg-gray-800 text-white p-4">
                        <Header />
                    </header>

                    {/* Main Content (bottom right) */}
                    <main className="bg-gray-100 p-6">{children}</main>
                </div>
            </body>
        </html>
    );
}
